name: peaklinn
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - scikit-learn=0.23
  - pip:
      # install peaklinn in the editable mode
      # so it is available in notebooks
      # and reflects changes in source code
      - -e .